/**
 * Tests for Configuration Utility
 * Comprehensive test coverage for all config constants and their values
 */

import {
  CONFIG,
  DEFAULT_USER_PREFERENCES,
  ERROR_MESSAGES,
  HTTP_STATUS,
} from '../../src/utils/config';

describe('Config Utility', () => {
  // ============================================================================
  // CONFIG Object Structure Tests
  // ============================================================================

  describe('CONFIG object structure', () => {
    test('CONFIG object exists and is defined', () => {
      expect(CONFIG).toBeDefined();
      expect(typeof CONFIG).toBe('object');
    });

    test('CONFIG has all required top-level properties', () => {
      expect(CONFIG).toHaveProperty('API_BASE_URL');
      expect(CONFIG).toHaveProperty('GOOGLE_OAUTH');
      expect(CONFIG).toHaveProperty('TOKEN');
      expect(CONFIG).toHaveProperty('STORAGE_KEYS');
      expect(CONFIG).toHaveProperty('TIMEOUTS');
    });

    test('CONFIG is readonly (const assertion)', () => {
      // CONFIG should have the readonly properties via const assertion
      // The actual object won't be frozen/sealed at runtime, but TypeScript treats it as readonly
      expect(CONFIG).toBeDefined();
      // Verify we can't add new properties (TypeScript will prevent this)
      const keys = Object.keys(CONFIG);
      expect(keys.length).toBe(6); // API_BASE_URL, NODE_ENV, GOOGLE_OAUTH, TOKEN, STORAGE_KEYS, TIMEOUTS
    });
  });

  // ============================================================================
  // API Configuration Tests
  // ============================================================================

  describe('CONFIG.API_BASE_URL', () => {
    test('API_BASE_URL is set correctly', () => {
      expect(CONFIG.API_BASE_URL).toBe('http://localhost:8080');
    });

    test('API_BASE_URL is a string', () => {
      expect(typeof CONFIG.API_BASE_URL).toBe('string');
    });

    test('API_BASE_URL is not empty', () => {
      expect(CONFIG.API_BASE_URL.length).toBeGreaterThan(0);
    });

    test('API_BASE_URL has valid URL format', () => {
      expect(CONFIG.API_BASE_URL).toMatch(/^https?:\/\//);
    });
  });

  // ============================================================================
  // Google OAuth Configuration Tests
  // ============================================================================

  describe('CONFIG.GOOGLE_OAUTH', () => {
    test('GOOGLE_OAUTH object exists', () => {
      expect(CONFIG.GOOGLE_OAUTH).toBeDefined();
      expect(typeof CONFIG.GOOGLE_OAUTH).toBe('object');
    });

    test('GOOGLE_OAUTH has CLIENT_ID property', () => {
      expect(CONFIG.GOOGLE_OAUTH).toHaveProperty('CLIENT_ID');
    });

    test('GOOGLE_OAUTH.CLIENT_ID is a non-empty string', () => {
      expect(typeof CONFIG.GOOGLE_OAUTH.CLIENT_ID).toBe('string');
      expect(CONFIG.GOOGLE_OAUTH.CLIENT_ID.length).toBeGreaterThan(0);
    });

    test('GOOGLE_OAUTH.CLIENT_ID has correct format', () => {
      // Google Client IDs typically follow this pattern: *.apps.googleusercontent.com
      expect(CONFIG.GOOGLE_OAUTH.CLIENT_ID).toMatch(/\.apps\.googleusercontent\.com$/);
    });

    test('GOOGLE_OAUTH has SCOPES property', () => {
      expect(CONFIG.GOOGLE_OAUTH).toHaveProperty('SCOPES');
    });

    test('GOOGLE_OAUTH.SCOPES is an array', () => {
      expect(Array.isArray(CONFIG.GOOGLE_OAUTH.SCOPES)).toBe(true);
    });

    test('GOOGLE_OAUTH.SCOPES contains required OAuth scopes', () => {
      expect(CONFIG.GOOGLE_OAUTH.SCOPES).toContain('openid');
      expect(CONFIG.GOOGLE_OAUTH.SCOPES).toContain('email');
      expect(CONFIG.GOOGLE_OAUTH.SCOPES).toContain('profile');
    });

    test('GOOGLE_OAUTH.SCOPES has exactly 3 scopes', () => {
      expect(CONFIG.GOOGLE_OAUTH.SCOPES).toHaveLength(3);
    });

    test('GOOGLE_OAUTH has REDIRECT_URI property', () => {
      expect(CONFIG.GOOGLE_OAUTH).toHaveProperty('REDIRECT_URI');
    });

    test('GOOGLE_OAUTH.REDIRECT_URI is a string', () => {
      expect(typeof CONFIG.GOOGLE_OAUTH.REDIRECT_URI).toBe('string');
    });

    test('GOOGLE_OAUTH.REDIRECT_URI is generated from chrome.identity API', () => {
      // The redirect URI should be generated by chrome.identity.getRedirectURL()
      expect(CONFIG.GOOGLE_OAUTH.REDIRECT_URI).toBe(chrome.identity.getRedirectURL());
    });
  });

  // ============================================================================
  // Token Management Configuration Tests
  // ============================================================================

  describe('CONFIG.TOKEN', () => {
    test('TOKEN object exists', () => {
      expect(CONFIG.TOKEN).toBeDefined();
      expect(typeof CONFIG.TOKEN).toBe('object');
    });

    test('TOKEN has REFRESH_THRESHOLD property', () => {
      expect(CONFIG.TOKEN).toHaveProperty('REFRESH_THRESHOLD');
    });

    test('TOKEN.REFRESH_THRESHOLD is a number', () => {
      expect(typeof CONFIG.TOKEN.REFRESH_THRESHOLD).toBe('number');
    });

    test('TOKEN.REFRESH_THRESHOLD is set to 5 minutes in milliseconds', () => {
      expect(CONFIG.TOKEN.REFRESH_THRESHOLD).toBe(5 * 60 * 1000);
      expect(CONFIG.TOKEN.REFRESH_THRESHOLD).toBe(300000);
    });

    test('TOKEN has MAX_RETRY_ATTEMPTS property', () => {
      expect(CONFIG.TOKEN).toHaveProperty('MAX_RETRY_ATTEMPTS');
    });

    test('TOKEN.MAX_RETRY_ATTEMPTS is a number', () => {
      expect(typeof CONFIG.TOKEN.MAX_RETRY_ATTEMPTS).toBe('number');
    });

    test('TOKEN.MAX_RETRY_ATTEMPTS is set to 3', () => {
      expect(CONFIG.TOKEN.MAX_RETRY_ATTEMPTS).toBe(3);
    });

    test('TOKEN has RETRY_DELAY property', () => {
      expect(CONFIG.TOKEN).toHaveProperty('RETRY_DELAY');
    });

    test('TOKEN.RETRY_DELAY is a number', () => {
      expect(typeof CONFIG.TOKEN.RETRY_DELAY).toBe('number');
    });

    test('TOKEN.RETRY_DELAY is set to 1 second in milliseconds', () => {
      expect(CONFIG.TOKEN.RETRY_DELAY).toBe(1000);
    });
  });

  // ============================================================================
  // Storage Keys Configuration Tests
  // ============================================================================

  describe('CONFIG.STORAGE_KEYS', () => {
    test('STORAGE_KEYS object exists', () => {
      expect(CONFIG.STORAGE_KEYS).toBeDefined();
      expect(typeof CONFIG.STORAGE_KEYS).toBe('object');
    });

    test('STORAGE_KEYS has AUTH_STATE property', () => {
      expect(CONFIG.STORAGE_KEYS).toHaveProperty('AUTH_STATE');
      expect(CONFIG.STORAGE_KEYS.AUTH_STATE).toBe('silence_notes_auth_state');
    });

    test('STORAGE_KEYS has USER_DATA property', () => {
      expect(CONFIG.STORAGE_KEYS).toHaveProperty('USER_DATA');
      expect(CONFIG.STORAGE_KEYS.USER_DATA).toBe('silence_notes_user_data');
    });

    test('STORAGE_KEYS has TOKENS property', () => {
      expect(CONFIG.STORAGE_KEYS).toHaveProperty('TOKENS');
      expect(CONFIG.STORAGE_KEYS.TOKENS).toBe('silence_notes_tokens');
    });

    test('STORAGE_KEYS has OAUTH_STATE property', () => {
      expect(CONFIG.STORAGE_KEYS).toHaveProperty('OAUTH_STATE');
      expect(CONFIG.STORAGE_KEYS.OAUTH_STATE).toBe('silence_notes_oauth_state');
    });

    test('STORAGE_KEYS has SETTINGS property', () => {
      expect(CONFIG.STORAGE_KEYS).toHaveProperty('SETTINGS');
      expect(CONFIG.STORAGE_KEYS.SETTINGS).toBe('silence_notes_settings');
    });

    test('STORAGE_KEYS has LAST_SYNC property', () => {
      expect(CONFIG.STORAGE_KEYS).toHaveProperty('LAST_SYNC');
      expect(CONFIG.STORAGE_KEYS.LAST_SYNC).toBe('silence_notes_last_sync');
    });

    test('All storage keys are strings', () => {
      expect(typeof CONFIG.STORAGE_KEYS.AUTH_STATE).toBe('string');
      expect(typeof CONFIG.STORAGE_KEYS.USER_DATA).toBe('string');
      expect(typeof CONFIG.STORAGE_KEYS.TOKENS).toBe('string');
      expect(typeof CONFIG.STORAGE_KEYS.OAUTH_STATE).toBe('string');
      expect(typeof CONFIG.STORAGE_KEYS.SETTINGS).toBe('string');
      expect(typeof CONFIG.STORAGE_KEYS.LAST_SYNC).toBe('string');
    });

    test('All storage keys follow the naming convention', () => {
      const keys = Object.values(CONFIG.STORAGE_KEYS);
      keys.forEach(key => {
        expect(key).toMatch(/^silence_notes_/);
      });
    });

    test('STORAGE_KEYS has exactly 6 properties', () => {
      expect(Object.keys(CONFIG.STORAGE_KEYS)).toHaveLength(6);
    });
  });

  // ============================================================================
  // Timeouts Configuration Tests
  // ============================================================================

  describe('CONFIG.TIMEOUTS', () => {
    test('TIMEOUTS object exists', () => {
      expect(CONFIG.TIMEOUTS).toBeDefined();
      expect(typeof CONFIG.TIMEOUTS).toBe('object');
    });

    test('TIMEOUTS has AUTH_FLOW property', () => {
      expect(CONFIG.TIMEOUTS).toHaveProperty('AUTH_FLOW');
    });

    test('TIMEOUTS.AUTH_FLOW is a number', () => {
      expect(typeof CONFIG.TIMEOUTS.AUTH_FLOW).toBe('number');
    });

    test('TIMEOUTS.AUTH_FLOW is set to 5 minutes in milliseconds', () => {
      expect(CONFIG.TIMEOUTS.AUTH_FLOW).toBe(5 * 60 * 1000);
      expect(CONFIG.TIMEOUTS.AUTH_FLOW).toBe(300000);
    });

    test('TIMEOUTS has TOKEN_REFRESH property', () => {
      expect(CONFIG.TIMEOUTS).toHaveProperty('TOKEN_REFRESH');
    });

    test('TIMEOUTS.TOKEN_REFRESH is a number', () => {
      expect(typeof CONFIG.TIMEOUTS.TOKEN_REFRESH).toBe('number');
    });

    test('TIMEOUTS.TOKEN_REFRESH is set to 30 seconds in milliseconds', () => {
      expect(CONFIG.TIMEOUTS.TOKEN_REFRESH).toBe(30 * 1000);
      expect(CONFIG.TIMEOUTS.TOKEN_REFRESH).toBe(30000);
    });

    test('TIMEOUTS has API_REQUEST property', () => {
      expect(CONFIG.TIMEOUTS).toHaveProperty('API_REQUEST');
    });

    test('TIMEOUTS.API_REQUEST is a number', () => {
      expect(typeof CONFIG.TIMEOUTS.API_REQUEST).toBe('number');
    });

    test('TIMEOUTS.API_REQUEST is set to 10 seconds in milliseconds', () => {
      expect(CONFIG.TIMEOUTS.API_REQUEST).toBe(10 * 1000);
      expect(CONFIG.TIMEOUTS.API_REQUEST).toBe(10000);
    });

    test('All timeout values are positive numbers', () => {
      expect(CONFIG.TIMEOUTS.AUTH_FLOW).toBeGreaterThan(0);
      expect(CONFIG.TIMEOUTS.TOKEN_REFRESH).toBeGreaterThan(0);
      expect(CONFIG.TIMEOUTS.API_REQUEST).toBeGreaterThan(0);
    });

    test('TIMEOUTS has exactly 3 properties', () => {
      expect(Object.keys(CONFIG.TIMEOUTS)).toHaveLength(3);
    });
  });

  // ============================================================================
  // Default User Preferences Tests
  // ============================================================================

  describe('DEFAULT_USER_PREFERENCES', () => {
    test('DEFAULT_USER_PREFERENCES object exists', () => {
      expect(DEFAULT_USER_PREFERENCES).toBeDefined();
      expect(typeof DEFAULT_USER_PREFERENCES).toBe('object');
    });

    test('DEFAULT_USER_PREFERENCES has theme property', () => {
      expect(DEFAULT_USER_PREFERENCES).toHaveProperty('theme');
    });

    test('DEFAULT_USER_PREFERENCES.theme is set to light', () => {
      expect(DEFAULT_USER_PREFERENCES.theme).toBe('light');
    });

    test('DEFAULT_USER_PREFERENCES has language property', () => {
      expect(DEFAULT_USER_PREFERENCES).toHaveProperty('language');
    });

    test('DEFAULT_USER_PREFERENCES.language is set to en', () => {
      expect(DEFAULT_USER_PREFERENCES.language).toBe('en');
    });

    test('DEFAULT_USER_PREFERENCES has timeZone property', () => {
      expect(DEFAULT_USER_PREFERENCES).toHaveProperty('timeZone');
    });

    test('DEFAULT_USER_PREFERENCES.timeZone is a string', () => {
      expect(typeof DEFAULT_USER_PREFERENCES.timeZone).toBe('string');
    });

    test('DEFAULT_USER_PREFERENCES.timeZone is derived from Intl API', () => {
      const expectedTimeZone = Intl.DateTimeFormat().resolvedOptions().timeZone;
      expect(DEFAULT_USER_PREFERENCES.timeZone).toBe(expectedTimeZone);
    });

    test('DEFAULT_USER_PREFERENCES has emailNotifications property', () => {
      expect(DEFAULT_USER_PREFERENCES).toHaveProperty('emailNotifications');
    });

    test('DEFAULT_USER_PREFERENCES.emailNotifications is set to true', () => {
      expect(DEFAULT_USER_PREFERENCES.emailNotifications).toBe(true);
    });

    test('DEFAULT_USER_PREFERENCES has autoSave property', () => {
      expect(DEFAULT_USER_PREFERENCES).toHaveProperty('autoSave');
    });

    test('DEFAULT_USER_PREFERENCES.autoSave is set to true', () => {
      expect(DEFAULT_USER_PREFERENCES.autoSave).toBe(true);
    });

    test('DEFAULT_USER_PREFERENCES has defaultNoteView property', () => {
      expect(DEFAULT_USER_PREFERENCES).toHaveProperty('defaultNoteView');
    });

    test('DEFAULT_USER_PREFERENCES.defaultNoteView is set to grid', () => {
      expect(DEFAULT_USER_PREFERENCES.defaultNoteView).toBe('grid');
    });

    test('DEFAULT_USER_PREFERENCES has exactly 6 properties', () => {
      expect(Object.keys(DEFAULT_USER_PREFERENCES)).toHaveLength(6);
    });

    test('All required preference properties are present', () => {
      const requiredKeys = [
        'theme',
        'language',
        'timeZone',
        'emailNotifications',
        'autoSave',
        'defaultNoteView'
      ];
      requiredKeys.forEach(key => {
        expect(DEFAULT_USER_PREFERENCES).toHaveProperty(key);
      });
    });
  });

  // ============================================================================
  // Error Messages Tests
  // ============================================================================

  describe('ERROR_MESSAGES', () => {
    test('ERROR_MESSAGES object exists', () => {
      expect(ERROR_MESSAGES).toBeDefined();
      expect(typeof ERROR_MESSAGES).toBe('object');
    });

    test('ERROR_MESSAGES has NETWORK_ERROR property', () => {
      expect(ERROR_MESSAGES).toHaveProperty('NETWORK_ERROR');
      expect(typeof ERROR_MESSAGES.NETWORK_ERROR).toBe('string');
      expect(ERROR_MESSAGES.NETWORK_ERROR.length).toBeGreaterThan(0);
    });

    test('ERROR_MESSAGES has AUTH_EXPIRED property', () => {
      expect(ERROR_MESSAGES).toHaveProperty('AUTH_EXPIRED');
      expect(typeof ERROR_MESSAGES.AUTH_EXPIRED).toBe('string');
      expect(ERROR_MESSAGES.AUTH_EXPIRED.length).toBeGreaterThan(0);
    });

    test('ERROR_MESSAGES has AUTH_REQUIRED property', () => {
      expect(ERROR_MESSAGES).toHaveProperty('AUTH_REQUIRED');
      expect(typeof ERROR_MESSAGES.AUTH_REQUIRED).toBe('string');
      expect(ERROR_MESSAGES.AUTH_REQUIRED.length).toBeGreaterThan(0);
    });

    test('ERROR_MESSAGES has INVALID_TOKEN property', () => {
      expect(ERROR_MESSAGES).toHaveProperty('INVALID_TOKEN');
      expect(typeof ERROR_MESSAGES.INVALID_TOKEN).toBe('string');
      expect(ERROR_MESSAGES.INVALID_TOKEN.length).toBeGreaterThan(0);
    });

    test('ERROR_MESSAGES has SERVER_ERROR property', () => {
      expect(ERROR_MESSAGES).toHaveProperty('SERVER_ERROR');
      expect(typeof ERROR_MESSAGES.SERVER_ERROR).toBe('string');
      expect(ERROR_MESSAGES.SERVER_ERROR.length).toBeGreaterThan(0);
    });

    test('ERROR_MESSAGES has OAUTH_ERROR property', () => {
      expect(ERROR_MESSAGES).toHaveProperty('OAUTH_ERROR');
      expect(typeof ERROR_MESSAGES.OAUTH_ERROR).toBe('string');
      expect(ERROR_MESSAGES.OAUTH_ERROR.length).toBeGreaterThan(0);
    });

    test('ERROR_MESSAGES has STORAGE_ERROR property', () => {
      expect(ERROR_MESSAGES).toHaveProperty('STORAGE_ERROR');
      expect(typeof ERROR_MESSAGES.STORAGE_ERROR).toBe('string');
      expect(ERROR_MESSAGES.STORAGE_ERROR.length).toBeGreaterThan(0);
    });

    test('ERROR_MESSAGES has UNKNOWN_ERROR property', () => {
      expect(ERROR_MESSAGES).toHaveProperty('UNKNOWN_ERROR');
      expect(typeof ERROR_MESSAGES.UNKNOWN_ERROR).toBe('string');
      expect(ERROR_MESSAGES.UNKNOWN_ERROR.length).toBeGreaterThan(0);
    });

    test('All error messages are non-empty strings', () => {
      Object.values(ERROR_MESSAGES).forEach(message => {
        expect(typeof message).toBe('string');
        expect(message.length).toBeGreaterThan(0);
      });
    });

    test('ERROR_MESSAGES has exactly 8 properties', () => {
      expect(Object.keys(ERROR_MESSAGES)).toHaveLength(8);
    });
  });

  // ============================================================================
  // HTTP Status Codes Tests
  // ============================================================================

  describe('HTTP_STATUS', () => {
    test('HTTP_STATUS object exists', () => {
      expect(HTTP_STATUS).toBeDefined();
      expect(typeof HTTP_STATUS).toBe('object');
    });

    test('HTTP_STATUS has OK property with value 200', () => {
      expect(HTTP_STATUS).toHaveProperty('OK');
      expect(HTTP_STATUS.OK).toBe(200);
    });

    test('HTTP_STATUS has CREATED property with value 201', () => {
      expect(HTTP_STATUS).toHaveProperty('CREATED');
      expect(HTTP_STATUS.CREATED).toBe(201);
    });

    test('HTTP_STATUS has BAD_REQUEST property with value 400', () => {
      expect(HTTP_STATUS).toHaveProperty('BAD_REQUEST');
      expect(HTTP_STATUS.BAD_REQUEST).toBe(400);
    });

    test('HTTP_STATUS has UNAUTHORIZED property with value 401', () => {
      expect(HTTP_STATUS).toHaveProperty('UNAUTHORIZED');
      expect(HTTP_STATUS.UNAUTHORIZED).toBe(401);
    });

    test('HTTP_STATUS has FORBIDDEN property with value 403', () => {
      expect(HTTP_STATUS).toHaveProperty('FORBIDDEN');
      expect(HTTP_STATUS.FORBIDDEN).toBe(403);
    });

    test('HTTP_STATUS has NOT_FOUND property with value 404', () => {
      expect(HTTP_STATUS).toHaveProperty('NOT_FOUND');
      expect(HTTP_STATUS.NOT_FOUND).toBe(404);
    });

    test('HTTP_STATUS has INTERNAL_SERVER_ERROR property with value 500', () => {
      expect(HTTP_STATUS).toHaveProperty('INTERNAL_SERVER_ERROR');
      expect(HTTP_STATUS.INTERNAL_SERVER_ERROR).toBe(500);
    });

    test('HTTP_STATUS has SERVICE_UNAVAILABLE property with value 503', () => {
      expect(HTTP_STATUS).toHaveProperty('SERVICE_UNAVAILABLE');
      expect(HTTP_STATUS.SERVICE_UNAVAILABLE).toBe(503);
    });

    test('All status codes are numbers', () => {
      Object.values(HTTP_STATUS).forEach(code => {
        expect(typeof code).toBe('number');
      });
    });

    test('All status codes are valid HTTP status codes', () => {
      Object.values(HTTP_STATUS).forEach(code => {
        expect(code).toBeGreaterThanOrEqual(100);
        expect(code).toBeLessThan(600);
      });
    });

    test('HTTP_STATUS has exactly 8 properties', () => {
      expect(Object.keys(HTTP_STATUS)).toHaveLength(8);
    });
  });

  // ============================================================================
  // Integration Tests
  // ============================================================================

  describe('Config Integration', () => {
    test('All config exports are available', () => {
      expect(CONFIG).toBeDefined();
      expect(DEFAULT_USER_PREFERENCES).toBeDefined();
      expect(ERROR_MESSAGES).toBeDefined();
      expect(HTTP_STATUS).toBeDefined();
    });

    test('Config values are consistent across the application', () => {
      // Verify that token refresh threshold equals auth flow timeout (both 5 minutes)
      expect(CONFIG.TOKEN.REFRESH_THRESHOLD).toBe(CONFIG.TIMEOUTS.AUTH_FLOW);
    });

    test('Timeout values are in proper order', () => {
      // API request should be fastest
      expect(CONFIG.TIMEOUTS.API_REQUEST).toBeLessThan(CONFIG.TIMEOUTS.TOKEN_REFRESH);
      // Token refresh should be faster than auth flow
      expect(CONFIG.TIMEOUTS.TOKEN_REFRESH).toBeLessThan(CONFIG.TIMEOUTS.AUTH_FLOW);
    });

    test('All numeric config values are positive', () => {
      expect(CONFIG.TOKEN.REFRESH_THRESHOLD).toBeGreaterThan(0);
      expect(CONFIG.TOKEN.MAX_RETRY_ATTEMPTS).toBeGreaterThan(0);
      expect(CONFIG.TOKEN.RETRY_DELAY).toBeGreaterThan(0);
      expect(CONFIG.TIMEOUTS.AUTH_FLOW).toBeGreaterThan(0);
      expect(CONFIG.TIMEOUTS.TOKEN_REFRESH).toBeGreaterThan(0);
      expect(CONFIG.TIMEOUTS.API_REQUEST).toBeGreaterThan(0);
    });

    test('Storage keys are unique', () => {
      const keys = Object.values(CONFIG.STORAGE_KEYS);
      const uniqueKeys = new Set(keys);
      expect(keys.length).toBe(uniqueKeys.size);
    });

    test('Error messages are descriptive', () => {
      Object.values(ERROR_MESSAGES).forEach(message => {
        expect(message.length).toBeGreaterThan(10);
      });
    });
  });

  // ============================================================================
  // Type Safety Tests
  // ============================================================================

  describe('Type Safety', () => {
    test('CONFIG maintains readonly structure', () => {
      // Verify CONFIG is properly typed as const
      const configKeys = Object.keys(CONFIG);
      expect(configKeys).toContain('API_BASE_URL');
      expect(configKeys).toContain('GOOGLE_OAUTH');
      expect(configKeys).toContain('TOKEN');
      expect(configKeys).toContain('STORAGE_KEYS');
      expect(configKeys).toContain('TIMEOUTS');
    });

    test('String properties maintain correct types', () => {
      expect(typeof CONFIG.API_BASE_URL).toBe('string');
      expect(typeof CONFIG.GOOGLE_OAUTH.CLIENT_ID).toBe('string');
      expect(typeof CONFIG.GOOGLE_OAUTH.REDIRECT_URI).toBe('string');
    });

    test('Number properties maintain correct types', () => {
      expect(typeof CONFIG.TOKEN.REFRESH_THRESHOLD).toBe('number');
      expect(typeof CONFIG.TOKEN.MAX_RETRY_ATTEMPTS).toBe('number');
      expect(typeof CONFIG.TOKEN.RETRY_DELAY).toBe('number');
      expect(typeof CONFIG.TIMEOUTS.AUTH_FLOW).toBe('number');
      expect(typeof CONFIG.TIMEOUTS.TOKEN_REFRESH).toBe('number');
      expect(typeof CONFIG.TIMEOUTS.API_REQUEST).toBe('number');
    });

    test('Array properties maintain correct types', () => {
      expect(Array.isArray(CONFIG.GOOGLE_OAUTH.SCOPES)).toBe(true);
    });

    test('Boolean preferences maintain correct types', () => {
      expect(typeof DEFAULT_USER_PREFERENCES.emailNotifications).toBe('boolean');
      expect(typeof DEFAULT_USER_PREFERENCES.autoSave).toBe('boolean');
    });
  });
});
